# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        rules:
            - { path: '^/api', priorities: [ 'json' ], fallback_format: json, prefer_extension: false }
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    body_listener: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    access_denied_listener:
#        json: true
#    view:
#        view_response_listener: 'force'
#        formats:
#            json: true
